### ISSUE TITLE
`Github Actions` 提示警告：`The following actions use a deprecated Node.js version and will be forced to run on node20: luizfelipelaviola/get-package-info@v1`

### ISSUE THREAD

**Issue by wangliang181230** [luizfelipelaviola/get-package-info#1]
The following actions use a deprecated Node.js version and will be forced to run on node20: `luizfelipelaviola/get-package-info@v1`. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

![图片](https://github.com/user-attachments/assets/ad33bdea-bd4f-4577-9c7d-142e4c59b0b2)

**Comment by luizfelipelaviola** [comment]
v2 is on https://github.com/luizfelipelaviola/get-package-info/releases/tag/v2
Thanks @wangliang181230
